version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=wb_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - WB_API_TOKEN=${WB_API_TOKEN}
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
    volumes:
      - .:/app
      - /app/node_modules